[fix] ci cd

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -15,7 +15,19 @@ jobs:
       - name: Checkout Code
         uses: actions/checkout@v4
 
-      # Шаг 2: Копирование файлов на сервер
+      # Шаг 2: Очистка и обновление директории на сервере
+      - name: Clean Target Directory on Server
+        uses: appleboy/ssh-action@master
+        with:
+          host: ${{ secrets.SERVER_HOST }}
+          username: ${{ secrets.SERVER_USER }}
+          key: ${{ secrets.SSH_PRIVATE_KEY }}
+          script: |
+            echo "Cleaning ~/myapp-directory"
+            rm -rf ~/myapp-directory || true
+            mkdir -p ~/myapp-directory
+
+      # Шаг 3: Копирование свежего кода на сервер
       - name: Copy Files to Server
         uses: appleboy/scp-action@master
         with:
@@ -26,34 +38,30 @@ jobs:
           target: "~/myapp-directory"
           strip-components: 0
 
-      # Шаг 3: Проверка файлов на сервере
-      - name: Check Files on Server
+      # Шаг 4: Сборка и деплой в Docker
+      - name: Build and Deploy with Docker
         uses: appleboy/ssh-action@master
         with:
           host: ${{ secrets.SERVER_HOST }}
           username: ${{ secrets.SERVER_USER }}
           key: ${{ secrets.SSH_PRIVATE_KEY }}
           script: |
-            echo "### Проверка директории ~/myapp-directory ###"
-            ls -R ~/myapp-directory
+            cd ~/myapp-directory/Sulpak.TestAssigment.PublicApi
 
-      # Шаг 4: Сборка и деплой
-      - name: Build and Deploy
-        uses: appleboy/ssh-action@master
-        with:
-          host: ${{ secrets.SERVER_HOST }}
-          username: ${{ secrets.SERVER_USER }}
-          key: ${{ secrets.SSH_PRIVATE_KEY }}
-          script: |
-            cd ~/myapp-directory
-            if [ ! -f ./Sulpak.TestAssigment.PublicApi/Dockerfile ]; then
-              echo "Error: Dockerfile not found in Sulpak.TestAssigment.PublicApi!"
+            # Проверка наличия Dockerfile
+            if [ ! -f Dockerfile ]; then
+              echo "Error: Dockerfile not found!"
               exit 1
             fi
 
+            echo "Stopping and removing existing container..."
             sudo docker stop myapp-container || true
             sudo docker rm myapp-container || true
-            sudo docker build -t myapp ./Sulpak.TestAssigment.PublicApi/
+
+            echo "Building Docker image..."
+            sudo docker build -t myapp .
+
+            echo "Running new container..."
             sudo docker run -d --name myapp-container -p 8080:8080 -p 8081:8081 myapp
 
             echo "Deployment completed successfully!"
